const songs = [
    {
        id: 0,
        name: 'Girls Like You',
        lyrics: [
            'Spent 24 hours, I need more hours with you',
            'You spent the weekend getting even, ooh',
            'We spent the late nights making things right between us',
            'But now it\'s all good, babe',
            'Roll that back wood, babe',
            'And play me close',
            'Cause girls like you run \'round with guys like me',
            'Til sun down when I come through',
            'I need a girl like you, yeah yeah',
            'Girls like you love fun, and yeah, me too',
            'What I want when I come through',
            'I need a girl like you, yeah yeah',
            'Yeah yeah yeah, yeah yeah yeah',
            'I need a girl like you, yeah yeah',
            'Yeah yeah yeah, yeah yeah yeah',
            'I need a girl like you',
            'I spent last night on the last flight to you',
            'Took a whole day up tryna get way up, ooh',
            'We spent the daylight tryna make things right between us',
            'But now it\'s all good, babe',
            'Roll that back wood, babe',
            'And play me close',
            'Cause girls like you run \'round with guys like me',
            'Til sun down when I come through',
            'I need a girl like you, yeah yeah',
            'Girls like you love fun, and yeah, me too',
            'What I want when I come through',
            'I need a girl like you, yeah yeah',
            'Yeah yeah yeah, yeah yeah yeah',
            'I need a girl like you, yeah yeah',
            'Yeah yeah yeah, yeah yeah yeah',
            'I need a girl like you, yeah yeah',
            'I need a girl like you, yeah yeah',
            'I need a girl like you',
            'Maybe it\'s 6:45',
            'Maybe I\'m barely alive',
            'Maybe you\'ve taken my shit for the last time',
            'Maybe I know that I\'m drunk',
            'Maybe I know you\'re the one',
            'Maybe you\'re thinking it\'s better if you drive',
            'Cause girls like you run \'round with guys like me',
            'Til sun down when I come through',
            'I need a girl like you, yeah',
            'Cause girls like you run \'round with guys like me',
            'Til sun down when I come through',
            'I need a girl like you, yeah yeah',
            'Girls like you love fun, and yeah, me too',
            'What I want when I come through',
            'I need a girl like you, yeah yeah',
            'Yeah yeah yeah, yeah yeah yeah',
            'I need a girl like you, yeah yeah',
            'Yeah yeah yeah, yeah yeah yeah',
            'I need a girl like you'
        ]
    },
    {
        id: 1,
        name: 'Love Yoreself',
        lyrics: [
            'For all the times that you rain on my parade',
            'And all the clubs you get in using my name',
            'You think you broke my heart, oh girl for goodness sake',
            'You think I\'m crying, on my own well I ain\'t',
            'And I didn\'t wanna write a song \'cause I didn\'t want anyone thinking I still care',
            'I don\'t but, you still hit my phone up',
            'And baby I be movin\' on and I think you should be somethin',
            'I don\'t wanna hold back, maybe you should know that',
            'My mama don\'t like you and she likes everyone',
            'And I never like to admit that I was wrong',
            'And I\'ve been so caught up in my job, didn\'t see what\'s going on',
            'But now I know, I\'m better sleeping on my own',
            'Cause if you like the way you look that much',
            'Oh baby you should go and love yourself',
            'And if you think that I\'m still holdin\' on to somethin',
            'You should go and love yourself',
            'When you told me that you hated my friends',
            'The only problem was with you and not them',
            'And every time you told me my opinion was wrong',
            'And tried to make me forget where I came from',
            'And I didn\'t wanna write a song cause I didn\'t want anyone thinking I still care',
            'I don\'t but, you still hit my phone up',
            'And baby I be movin\' on and I think you should be somethin',
            'I don\'t wanna hold back, maybe you should know that',
            'My mama don\'t like you and she likes everyone',
            'And I never like to admit that I was wrong',
            'And I\'ve been so caught up in my job, didn\'t see what\'s going on',
            'But now I know, I\'m better sleeping on my own',
            'Cause if you like the way you look that much',
            'Oh baby you should go and love yourself',
            'And if you think that I\'m still holdin\' on to somethin',
            'You should go and love yourself',
            'For all the times you made me feel small',
            'I fell in love, now I feel nothin\' at all',
            'I never felt so low when I was vulnerable',
            'Was I a fool to let you break down my walls?',
            'Cause if you like the way you look that much',
            'Oh baby you should go and love yourself',
            'And if you think that I\'m still holdin\' on to somethin',
            'You should go and love yourself',
            'Cause if you like the way you look that much',
            'Oh baby you should go and love yourself (yeah)',
            'And if you think (you think) that I\'m (that I\'m)',
            'Still holdin\' on (holdin on), to somethin\'',
            'You should go and love yourself'
        ]
    },
    {
        id: 2,
        name: 'All We Know',
        lyrics: [
            'Fighting flames of fire',
            'Hang onto burning wires',
            'We don\'t care anymore',
            'Are we fading lovers?',
            'We keep wasting colors',
            'Maybe we should let this go',
            'We\'re falling apart, still we hold together',
            'We\'ve passed the end, so we chase forever',
            'Cause this is all we know',
            'This feeling\'s all we know',
            'I\'ll ride my bike up to the road',
            'Down the streets right through the city',
            'I\'ll go everywhere you go',
            'From Chicago to the coast',
            'You tell me, Hit this and let\'s go',
            'Blow the smoke right through the window',
            'Cause this is all we know',
            'Cause this is all we know',
            'Cause this is all we know',
            'Never face each other',
            'One bed, different covers',
            'We don\'t care anymore',
            'Two hearts still beating',
            'On with different rhythms',
            'Maybe we should let this go',
            'We\'re falling apart, still we hold together',
            'We\'ve passed the end, so we chase forever',
            'Cause this is all we know',
            'This feeling\'s all we know',
            'I\'ll ride my bike up to the road',
            'Down the streets right through the city',
            'I\'ll go everywhere you go',
            'From Chicago to the coast',
            'You tell me, Hit this and let\'s go',
            'Blow the smoke right through the window',
            'Cause this is all we know',
            'Cause this is all we know',
            'Cause this is all we know',
        ]
    }
]
